name: Build and Release Disk Erasure Tool

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Read base version and append build number
      - name: Generate version
        id: version
        shell: bash
        run: |
          VERSION_FILE="version.txt"

          if [ ! -f "$VERSION_FILE" ]; then
            echo "1.0.0" > $VERSION_FILE
          fi

          BASE_VERSION=$(cat $VERSION_FILE)
          FINAL_VERSION="${BASE_VERSION}-${GITHUB_RUN_NUMBER}"

          echo "version=$FINAL_VERSION" >> $GITHUB_OUTPUT

      # Update EXE metadata
      - name: Update metadata version
        shell: bash
        run: |
          VERSION=${{ steps.version.outputs.version }}

          sed -i "s/FileVersion', '.*'/FileVersion', '$VERSION'/" version_info.txt
          sed -i "s/ProductVersion', '.*'/ProductVersion', '$VERSION'/" version_info.txt

      # Build EXE
      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed \
          --name DiskErasureTool \
          --version-file version_info.txt \
          --collect-all usb \
          --collect-all escpos \
          DiskErasureUI.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DiskErasureTool
          path: dist/DiskErasureTool.exe


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: DiskErasureTool
          path: release

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Disk Erasure Tool v${{ needs.build.outputs.version }}
          files: release/DiskErasureTool.exe
          generate_release_notes: true
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}